Bump version of spf13/pflag lib
because of:
```
go test github.com/AirHelp/treasury/client
../../go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:31:25: undefined: pflag.ParseErrorsWhitelist
```