Fix bats test for wrong AWS region
SSM backend returns:
```
./treasury read development/treasury/key1 -r asdad
Error: RequestError: send request failed
caused by: Post https://ssm.asdad.amazonaws.com/: dial tcp: lookup ssm.asdad.amazonaws.com: no such host
```