Add negative template bats test
```
 ./treasury template --src test/resources/bats-wrong-source.secret.tpl --dst test/output/bats-output.secret ; echo $?
Error: template: templateCli:1:26: executing "templateCli" at <read "development/tr...>: error calling read: NoSuchKey: The specified key does not exist.
	status code: 404, request id: E21164000E788272
Usage:
  treasury template --src TEMPLATE_FILE --dst DESTINATION_FILE [flags]

Flags:
      --dst string   destination file path
      --perms int    destination file permission, e.g.: 0644
      --src string   template file path

Global Flags:
  -r, --region string   s3 region

template: templateCli:1:26: executing "templateCli" at <read "development/tr...>: error calling read: NoSuchKey: The specified key does not exist.
	status code: 404, request id: E21164000E788272
255
```